swagger: "2.0"
  
info:
  version: 1.0.0
  title: Legacy Sub-API
  description: Legacy operations

securityDefinitions:
  $ref: commons.yaml#/securityDefinitions

paths:
  /js-less-consumer-persons:
    parameters:
      - $ref: 'commons.yaml#/parameters/userAgent'
    post:
      summary: Creates a person
      description: For JS-less partners
      operationId: createUserJS
      deprecated: true
      tags:
        - JSLess
        - Persons
      security:
        - OauthSecurity:
          - admin
        - LegacySecurity: []
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - text/html
      parameters:
        - name: username
          in: formData
          required: true
          pattern: '[a-z0-9]{8,64}'
          minLength: 8
          maxLength: 64
          type: string
        - name: firstname
          in: formData
          type: string
        - name: lastname
          in: formData
          type: string
        - name: dateOfBirth
          in: formData
          type: string
          format: date
      responses:
        '204':
          description: Person succesfully created.
          headers:
            $ref: 'commons.yaml#/responses/DefaultHeaders/headers'
        '400':
          description: Person couldn't have been created.
          headers:
            $ref: 'commons.yaml#/responses/DefaultHeaders/headers'
        '500':
          description: An error occured.
          headers:
            $ref: 'commons.yaml#/responses/DefaultHeaders/headers'
        default:
          $ref: 'commons.yaml#/responses/TotallyUnexpectedResponse'