name: Clear Cloudflare Cache

on:
  push:
    branches: [ gh-pages-test ]

jobs:
  clear_cache:
    env:
      POSTMAN_COLLECTION_BRANCH: master
      POSTMAN_COLLECTION_FOLDER: scripts
      CLOUDFLARE_WEBSITE: apihandyman.io
    runs-on: ubuntu-latest
    steps:
      - name: ‚¨áÔ∏è Checkout ${{env.POSTMAN_COLLECTION_BRANCH}} branch to get Cloudflare Clear Cache Postman collection
        uses: actions/checkout@v2
        with:
          ref: ${{env.POSTMAN_COLLECTION_BRANCH}}
          fetch-depth: 1
      - name: üí• Clear Cloudflare cache
        run: |
          docker run \
          -v ${{ github.workspace }}/${{env.POSTMAN_COLLECTION_FOLDER}}:/etc/newman \
          -t postman/newman:alpine run \
          --global-var token=${{secrets.CLOUDFLARE_TOKEN}} \
          --global-var website=${{env.CLOUDFLARE_WEBSITE}} \
          cloudflare-clearcache.postman_collection.json
