name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_publish:
    env:
      PUBLISH_BRANCH: gh-pages-test
      PUBLISH_BRANCH_FOLDER: _site
    runs-on: ubuntu-latest
    steps:
    - name: ‚¨áÔ∏è Checkout current branch
      uses: actions/checkout@v2
      with:
          fetch-depth: 1
    - name: üë∑üèª‚Äç‚ôÇÔ∏è Build with jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/${{env.PUBLISH_BRANCH_FOLDER}}:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: üöÄ Push on ${{env.PUBLISH_BRANCH}}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: ${{env.PUBLISH_BRANCH}} # The branch the action should deploy to.
        folder: ${{ github.workspace }}/${{env.PUBLISH_BRANCH_FOLDER}} # The folder the action should deploy.        
        token: ${{secrets.GH_TOKEN}} # Needed to trigger action on target branch (without it no action will be triggered)
        clean: true
        commit-message: Publish
  clear_cdn_cache:
    needs: [ publish ]
    env:
      POSTMAN_COLLECTION_BRANCH: master
      POSTMAN_COLLECTION_FOLDER: scripts
      CLOUDFLARE_WEBSITE: apihandyman.io
    runs-on: ubuntu-latest
    steps:
      - name: ‚¨áÔ∏è Download Cloudflare Clear Cache Postman collection
        uses: actions/checkout@v2
        with:
          ref: ${{env.POSTMAN_COLLECTION_BRANCH}}
          fetch-depth: 1
      - name: üí• Clear Cloudflare cache
        run: |
          docker run \
          -v ${{ github.workspace }}/${{env.POSTMAN_COLLECTION_FOLDER}}:/etc/newman \
          -t postman/newman:alpine run \
          --global-var token=${{secrets.CLOUDFLARE_TOKEN}} \
          --global-var website=${{env.CLOUDFLARE_WEBSITE}} \
          cloudflare-clearcache.postman_collection.json
